version: '2'
services:
  generatedata:
    build: .
    ports:
      - "127.0.0.1:1111:80"
    networks:
      default:
        ipv4_address: 172.16.111.101
    depends_on:
      - generatedata_db
    links:
      - generatedata_db
  generatedata_db:
    image: "percona:5.6"
    ports:
      - "127.0.0.1:1112:3306"
    networks:
      default:
        ipv4_address: 172.16.111.102
    environment:
      - MYSQL_ROOT_PASSWORD=dockerization
      - MYSQL_DATABASE=generatedata
      - MYSQL_PASSWORD=
    volumes:
      - ./var/percona:/var/lib/mysql

networks:
  default:
    external:
      name: dockerization_net
